name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token configured in Repository Secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # 1. Enable Coding Habits plugin
          plugin_habits: yes
          plugin_habits_facts: yes      # Display mildly interesting facts
          plugin_habits_charts: yes     # Display charts

          # 2. Enable Starred Repositories plugin
          plugin_stars: yes
          plugin_stars_limit: 4         # Limit the number of repositories displayed

          # 3. Enable Starred Topics plugin
          plugin_topics: yes
          plugin_topics_limit: 15       # Limit the number of topics displayed
          plugin_topics_mode: icons     # Choose layout: "icons" or "labels"
